/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FoodSupplierRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.TransportEnterprise;
import Business.Network.Network;
import Business.Organization.FoodSupplierOrganization;
import Business.Organization.Organization;
import Business.Organization.TransportDistributorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodSupplierWorkRequest;
import Business.WorkQueue.TransportDistributorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sheetal Sekhar
 */
public class FoodSupplierWorkAreaJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount account;
    private Organization organization;
    private FoodSupplierOrganization foodSupplierOrganization;
    private WorkRequest request;
    private Enterprise enterprise;
    
    
    
    
    /**
     * Creates new form FoodSupplierWorkAreaJPanel
     */
    public FoodSupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise)
    {
        
        
        initComponents();
    this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.foodSupplierOrganization = (FoodSupplierOrganization)organization;
        valueLabel5.setText(enterprise.getName());
      valueLabel2.setText(account.getUsername());
      assignJButton.setEnabled(true);
        processJButton.setEnabled(true);
        transportBtn.setEnabled(false);
        
        populateTable();
        populateTable1();
   
    }
    
    
    public void populateTable(){
       
       DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();

       model.setRowCount(0);

       for(WorkRequest request : foodSupplierOrganization.getWorkQueue().getWorkRequestList()){
           Object[] row = new Object[8];
           row[6] = request;
           row[0]= request.getId();
           row[1]= request.getAddress();
           row[2]=request.getZipcode();
           row[3] = request.getSender().getEmployee().getName();
           row[4] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
           row[5]= request.getStatus();
           row[7]= request.getSenderEmail();
           model.addRow(row);
       }
   }
    

    
 
                public void populateTable1() {
       DefaultTableModel model = (DefaultTableModel)TrasportDJTable.getModel();

       model.setRowCount(0);

      for(Network n: business.getNetworkList()){
           for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
               if(e instanceof TransportEnterprise){
                   System.out.println("In trasport Enterprise");
                   for (Organization organization1 : e.getOrganizationDirectory().getOrganizationList()){
       for(WorkRequest req :organization1.getWorkQueue().getWorkRequestList()){
           Object[] row = new Object[5];
           row[0] = req;
           row[1]= req.getMessage();
           row[2]=req.getAddress();
           row[3]=req.getZipcode();
           row[4] = req.getStatus();

           model.addRow(row);
       }
   }
               }
           }
      }
 }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        refreshJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        enterpriseLabel2 = new javax.swing.JLabel();
        valueLabel2 = new javax.swing.JLabel();
        valueLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        transportBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TrasportDJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request-ID", "Address", "Zip Code", "Requested By", "Supplied By", "Status", "Date", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 690, 100));

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel2.setText("EnterPrise :");
        jPanel2.add(enterpriseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, -1));

        valueLabel2.setText("<value>");
        jPanel2.add(valueLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 120, -1));

        valueLabel5.setText("<value>");
        jPanel2.add(valueLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, -1));

        jLabel1.setText("Logged in as:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 100, -1));

        transportBtn.setText("Request To Deliver");
        transportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportBtnActionPerformed(evt);
            }
        });
        jPanel2.add(transportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        TrasportDJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Message", "Address", "ZipCode", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TrasportDJTable);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 370, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Food Supplier Work Area");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Food Work Request");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Manage Transport Request List");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
         populateTable1();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
    assignJButton.setEnabled(true);
processJButton.setEnabled(true);
transportBtn.setEnabled(false);
       int selectedRow = workRequestJTable.getSelectedRow();

       if (selectedRow < 0){
           return;
       }

       WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 6);
       request.setReceiver(account);
       request.setStatus("Pending");
       populateTable();
        
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
      assignJButton.setEnabled(false);
processJButton.setEnabled(false);
transportBtn.setEnabled(true);
       int selectedRow = workRequestJTable.getSelectedRow();

      if (selectedRow < 0){
          return;
      }
      //request.setStatus("Processing");
      WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 6);
      System.out.println(request);
      //request.setStatus("Processing");

      SupplierProcessRequest foodSupplierProcessRequest = new SupplierProcessRequest(userProcessContainer,request);
      userProcessContainer.add("clothesSupplierProcessRequest", foodSupplierProcessRequest);
      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void transportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportBtnActionPerformed
       int selectedRow = workRequestJTable.getSelectedRow();

       if (selectedRow < 0){
           return;
       }

      WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 6);
       assignJButton.setEnabled(false);
   processJButton.setEnabled(false);
WorkRequest request1 = new TransportDistributorWorkRequest();

       request1.setAddress(request.getAddress());
       request1.setSenderEmail(request.getSenderEmail());
       System.out.println(request.getAddress());
       request1.setAddress(request.getZipcode());

      request.setStatus("Sent");


      Organization org = null;
      for(Network n: business.getNetworkList()){
          for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
              if(e instanceof TransportEnterprise){
                  System.out.println("In trasport Enterprise");
                  for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                      if (organization instanceof TransportDistributorOrganization){
                          org = organization;
                          System.out.println(org);
                          break;
                      }
                  }
              }

          }

      }

      if (org!=null){
          org.getWorkQueue().getWorkRequestList().add(request);
          System.out.println(org);
          System.out.println(request.toString());
          account.getWorkQueue().getWorkRequestList().add(request);
       }
      populateTable1();
    }//GEN-LAST:event_transportBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TrasportDJTable;
    private javax.swing.JButton assignJButton;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton transportBtn;
    private javax.swing.JLabel valueLabel2;
    private javax.swing.JLabel valueLabel5;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
