/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClothesConsumerRole;


import Business.Enterprise.Enterprise;
import Business.Organization.ClothingSupplierOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ClothingSupplierWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author priya
 */
public class ClothesRequestJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
 
    /**
     * Creates new form ClothesRequestJPanel
     */
    public ClothesRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
         valueLabel1.setText(enterprise.getName());
        valueLabel5.setText(account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        requestTestJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        valueLabel1 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zipCodejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        boyjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        girljTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        menjTextFiel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        womenjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        valueLabel5 = new javax.swing.JLabel();
        emailwarning1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton1.setText("Request ");
        requestTestJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(requestTestJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        backJButton1.setText("<<Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        valueLabel1.setText("<value>");
        jPanel2.add(valueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("EnterPrise :");
        jPanel2.add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 30));

        jLabel3.setText("Address:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));
        jPanel2.add(addressjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 90, -1));

        jLabel4.setText("ZipCode:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));
        jPanel2.add(zipCodejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, -1));

        jLabel1.setText("Boys:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));
        jPanel2.add(boyjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 30, -1));

        jLabel5.setText("Girls:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        jPanel2.add(girljTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 30, -1));

        jLabel6.setText("Men:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
        jPanel2.add(menjTextFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 30, -1));

        jLabel7.setText("Women:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        womenjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                womenjTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(womenjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 30, -1));

        jLabel8.setText("Enter values for the following categories");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, -1));

        jLabel9.setText("Logged in as:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        valueLabel5.setText("<value>");
        jPanel2.add(valueLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));
        jPanel2.add(emailwarning1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 140, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton1ActionPerformed
      String address = addressjTextField.getText();    
   try
       {
           Integer.parseInt(menjTextFiel.getText());
       }
       catch (NumberFormatException ec)
       {
       JOptionPane.showMessageDialog(null, "Availibity is only in numbers, not text. try Again");
           return;
       }

try
{
Integer.parseInt(womenjTextField.getText());
}
catch (NumberFormatException ec)
       {
       JOptionPane.showMessageDialog(null, "Availibity is only in numbers, not text. try Again");
           return;
       }
try
{
Integer.parseInt(zipCodejTextField.getText());
}
catch (NumberFormatException ec)
       {
       JOptionPane.showMessageDialog(null, "Availibity is only in numbers, not text. try Again");
           return;
       }

try
{
Integer.parseInt(boyjTextField.getText());
}
catch (NumberFormatException ec)
       {
       JOptionPane.showMessageDialog(null, "Availibity is only in numbers, not text. try Again");
           return;
       }

try
{
Integer.parseInt(girljTextField.getText());
}
catch (NumberFormatException ec)
       {
       JOptionPane.showMessageDialog(null, "Availibity is only in numbers, not text. try Again");
           return;
       }


       ClothingSupplierWorkRequest request = new ClothingSupplierWorkRequest();
       //request.setBoy(boy);
       //request.setGirl(girl);
      // request.setMen(men);
       request.setMen(Integer.parseInt(menjTextFiel.getText()));
       request.setWomen(Integer.parseInt(womenjTextField.getText()));
       request.setWomen(Integer.parseInt(girljTextField.getText()));
       request.setWomen(Integer.parseInt(boyjTextField.getText()));
       request.setSender(userAccount);
       request.setStatus("Request Sent");
       request.setAddress(address);
       request.setZipcode(zipCodejTextField.getText());
       request.setSenderEmail(userAccount.getEmail());
       //request.setZipcode(zipCode);
       request.setMen(Integer.parseInt(zipCodejTextField.getText()));
       request.setReceiver(userAccount);

       Organization org = null;
       for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
           if (organization instanceof ClothingSupplierOrganization){
               org = organization;
               break;
           }
       }
       if (org!=null){
           org.getWorkQueue().getWorkRequestList().add(request);
           userAccount.getWorkQueue().getWorkRequestList().add(request);
       }
        JOptionPane.showMessageDialog(null, "Request Created Successfully");
 

    }//GEN-LAST:event_requestTestJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClothesConsumerWorkAreaJPanel dwjp = (ClothesConsumerWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void womenjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_womenjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_womenjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjTextField;
    private javax.swing.JButton backJButton1;
    private javax.swing.JTextField boyjTextField;
    private javax.swing.JLabel emailwarning1;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JTextField girljTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField menjTextFiel;
    private javax.swing.JButton requestTestJButton1;
    private javax.swing.JLabel valueLabel1;
    private javax.swing.JLabel valueLabel5;
    private javax.swing.JTextField womenjTextField;
    private javax.swing.JTextField zipCodejTextField;
    // End of variables declaration//GEN-END:variables
}
